name: dsx_compiler
description: Minimal DSX -> Dart compiler (MVP with hoist & robust CLI). Fixed event handlers.
version: 0.0.5
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  args: ^2.7.0
  path: ^1.9.1
  glob: ^2.1.3
